// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Order_SeckillOrder_FullMethodName           = "/order.Order/SeckillOrder"
	Order_CreateSeckillActivity_FullMethodName  = "/order.Order/CreateSeckillActivity"
	Order_GetSeckillActivity_FullMethodName     = "/order.Order/GetSeckillActivity"
	Order_LoadSeckillStock_FullMethodName       = "/order.Order/LoadSeckillStock"
	Order_GetSeckillOrder_FullMethodName        = "/order.Order/GetSeckillOrder"
	Order_GetUserSeckillOrders_FullMethodName   = "/order.Order/GetUserSeckillOrders"
	Order_CancelTimeoutOrder_FullMethodName     = "/order.Order/CancelTimeoutOrder"
	Order_CreatePayment_FullMethodName          = "/order.Order/CreatePayment"
	Order_ProcessPaymentCallback_FullMethodName = "/order.Order/ProcessPaymentCallback"
	Order_QueryPayment_FullMethodName           = "/order.Order/QueryPayment"
	Order_Refund_FullMethodName                 = "/order.Order/Refund"
	Order_CloseOrder_FullMethodName             = "/order.Order/CloseOrder"
)

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderClient interface {
	SeckillOrder(ctx context.Context, in *SeckillOrderRequest, opts ...grpc.CallOption) (*SeckillOrderResponse, error)
	CreateSeckillActivity(ctx context.Context, in *CreateSeckillActivityRequest, opts ...grpc.CallOption) (*CreateSeckillActivityResponse, error)
	GetSeckillActivity(ctx context.Context, in *GetSeckillActivityRequest, opts ...grpc.CallOption) (*GetSeckillActivityResponse, error)
	LoadSeckillStock(ctx context.Context, in *LoadSeckillStockRequest, opts ...grpc.CallOption) (*LoadSeckillStockResponse, error)
	GetSeckillOrder(ctx context.Context, in *GetSeckillOrderRequest, opts ...grpc.CallOption) (*GetSeckillOrderResponse, error)
	GetUserSeckillOrders(ctx context.Context, in *GetUserSeckillOrdersRequest, opts ...grpc.CallOption) (*GetUserSeckillOrdersResponse, error)
	CancelTimeoutOrder(ctx context.Context, in *CancelTimeoutOrderRequest, opts ...grpc.CallOption) (*CancelTimeoutOrderResponse, error)
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	ProcessPaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackResponse, error)
	QueryPayment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentResponse, error)
	Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error)
	CloseOrder(ctx context.Context, in *CloseOrderRequest, opts ...grpc.CallOption) (*CloseOrderResponse, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) SeckillOrder(ctx context.Context, in *SeckillOrderRequest, opts ...grpc.CallOption) (*SeckillOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeckillOrderResponse)
	err := c.cc.Invoke(ctx, Order_SeckillOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateSeckillActivity(ctx context.Context, in *CreateSeckillActivityRequest, opts ...grpc.CallOption) (*CreateSeckillActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSeckillActivityResponse)
	err := c.cc.Invoke(ctx, Order_CreateSeckillActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetSeckillActivity(ctx context.Context, in *GetSeckillActivityRequest, opts ...grpc.CallOption) (*GetSeckillActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeckillActivityResponse)
	err := c.cc.Invoke(ctx, Order_GetSeckillActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) LoadSeckillStock(ctx context.Context, in *LoadSeckillStockRequest, opts ...grpc.CallOption) (*LoadSeckillStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadSeckillStockResponse)
	err := c.cc.Invoke(ctx, Order_LoadSeckillStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetSeckillOrder(ctx context.Context, in *GetSeckillOrderRequest, opts ...grpc.CallOption) (*GetSeckillOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeckillOrderResponse)
	err := c.cc.Invoke(ctx, Order_GetSeckillOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetUserSeckillOrders(ctx context.Context, in *GetUserSeckillOrdersRequest, opts ...grpc.CallOption) (*GetUserSeckillOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSeckillOrdersResponse)
	err := c.cc.Invoke(ctx, Order_GetUserSeckillOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CancelTimeoutOrder(ctx context.Context, in *CancelTimeoutOrderRequest, opts ...grpc.CallOption) (*CancelTimeoutOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTimeoutOrderResponse)
	err := c.cc.Invoke(ctx, Order_CancelTimeoutOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, Order_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) ProcessPaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentCallbackResponse)
	err := c.cc.Invoke(ctx, Order_ProcessPaymentCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) QueryPayment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPaymentResponse)
	err := c.cc.Invoke(ctx, Order_QueryPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundResponse)
	err := c.cc.Invoke(ctx, Order_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CloseOrder(ctx context.Context, in *CloseOrderRequest, opts ...grpc.CallOption) (*CloseOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseOrderResponse)
	err := c.cc.Invoke(ctx, Order_CloseOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
// All implementations must embed UnimplementedOrderServer
// for forward compatibility.
type OrderServer interface {
	SeckillOrder(context.Context, *SeckillOrderRequest) (*SeckillOrderResponse, error)
	CreateSeckillActivity(context.Context, *CreateSeckillActivityRequest) (*CreateSeckillActivityResponse, error)
	GetSeckillActivity(context.Context, *GetSeckillActivityRequest) (*GetSeckillActivityResponse, error)
	LoadSeckillStock(context.Context, *LoadSeckillStockRequest) (*LoadSeckillStockResponse, error)
	GetSeckillOrder(context.Context, *GetSeckillOrderRequest) (*GetSeckillOrderResponse, error)
	GetUserSeckillOrders(context.Context, *GetUserSeckillOrdersRequest) (*GetUserSeckillOrdersResponse, error)
	CancelTimeoutOrder(context.Context, *CancelTimeoutOrderRequest) (*CancelTimeoutOrderResponse, error)
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	ProcessPaymentCallback(context.Context, *PaymentCallbackRequest) (*PaymentCallbackResponse, error)
	QueryPayment(context.Context, *QueryPaymentRequest) (*QueryPaymentResponse, error)
	Refund(context.Context, *RefundRequest) (*RefundResponse, error)
	CloseOrder(context.Context, *CloseOrderRequest) (*CloseOrderResponse, error)
	mustEmbedUnimplementedOrderServer()
}

// UnimplementedOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServer struct{}

func (UnimplementedOrderServer) SeckillOrder(context.Context, *SeckillOrderRequest) (*SeckillOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SeckillOrder not implemented")
}
func (UnimplementedOrderServer) CreateSeckillActivity(context.Context, *CreateSeckillActivityRequest) (*CreateSeckillActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSeckillActivity not implemented")
}
func (UnimplementedOrderServer) GetSeckillActivity(context.Context, *GetSeckillActivityRequest) (*GetSeckillActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeckillActivity not implemented")
}
func (UnimplementedOrderServer) LoadSeckillStock(context.Context, *LoadSeckillStockRequest) (*LoadSeckillStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadSeckillStock not implemented")
}
func (UnimplementedOrderServer) GetSeckillOrder(context.Context, *GetSeckillOrderRequest) (*GetSeckillOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeckillOrder not implemented")
}
func (UnimplementedOrderServer) GetUserSeckillOrders(context.Context, *GetUserSeckillOrdersRequest) (*GetUserSeckillOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSeckillOrders not implemented")
}
func (UnimplementedOrderServer) CancelTimeoutOrder(context.Context, *CancelTimeoutOrderRequest) (*CancelTimeoutOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTimeoutOrder not implemented")
}
func (UnimplementedOrderServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedOrderServer) ProcessPaymentCallback(context.Context, *PaymentCallbackRequest) (*PaymentCallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPaymentCallback not implemented")
}
func (UnimplementedOrderServer) QueryPayment(context.Context, *QueryPaymentRequest) (*QueryPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryPayment not implemented")
}
func (UnimplementedOrderServer) Refund(context.Context, *RefundRequest) (*RefundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedOrderServer) CloseOrder(context.Context, *CloseOrderRequest) (*CloseOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseOrder not implemented")
}
func (UnimplementedOrderServer) mustEmbedUnimplementedOrderServer() {}
func (UnimplementedOrderServer) testEmbeddedByValue()               {}

// UnsafeOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServer will
// result in compilation errors.
type UnsafeOrderServer interface {
	mustEmbedUnimplementedOrderServer()
}

func RegisterOrderServer(s grpc.ServiceRegistrar, srv OrderServer) {
	// If the following call panics, it indicates UnimplementedOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Order_ServiceDesc, srv)
}

func _Order_SeckillOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeckillOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).SeckillOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_SeckillOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).SeckillOrder(ctx, req.(*SeckillOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateSeckillActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSeckillActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateSeckillActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CreateSeckillActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateSeckillActivity(ctx, req.(*CreateSeckillActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetSeckillActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeckillActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetSeckillActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetSeckillActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetSeckillActivity(ctx, req.(*GetSeckillActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_LoadSeckillStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadSeckillStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).LoadSeckillStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_LoadSeckillStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).LoadSeckillStock(ctx, req.(*LoadSeckillStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetSeckillOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeckillOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetSeckillOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetSeckillOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetSeckillOrder(ctx, req.(*GetSeckillOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetUserSeckillOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSeckillOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetUserSeckillOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetUserSeckillOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetUserSeckillOrders(ctx, req.(*GetUserSeckillOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CancelTimeoutOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTimeoutOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CancelTimeoutOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CancelTimeoutOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CancelTimeoutOrder(ctx, req.(*CancelTimeoutOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_ProcessPaymentCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).ProcessPaymentCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_ProcessPaymentCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).ProcessPaymentCallback(ctx, req.(*PaymentCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_QueryPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).QueryPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_QueryPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).QueryPayment(ctx, req.(*QueryPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CloseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CloseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CloseOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CloseOrder(ctx, req.(*CloseOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Order_ServiceDesc is the grpc.ServiceDesc for Order service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Order_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SeckillOrder",
			Handler:    _Order_SeckillOrder_Handler,
		},
		{
			MethodName: "CreateSeckillActivity",
			Handler:    _Order_CreateSeckillActivity_Handler,
		},
		{
			MethodName: "GetSeckillActivity",
			Handler:    _Order_GetSeckillActivity_Handler,
		},
		{
			MethodName: "LoadSeckillStock",
			Handler:    _Order_LoadSeckillStock_Handler,
		},
		{
			MethodName: "GetSeckillOrder",
			Handler:    _Order_GetSeckillOrder_Handler,
		},
		{
			MethodName: "GetUserSeckillOrders",
			Handler:    _Order_GetUserSeckillOrders_Handler,
		},
		{
			MethodName: "CancelTimeoutOrder",
			Handler:    _Order_CancelTimeoutOrder_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _Order_CreatePayment_Handler,
		},
		{
			MethodName: "ProcessPaymentCallback",
			Handler:    _Order_ProcessPaymentCallback_Handler,
		},
		{
			MethodName: "QueryPayment",
			Handler:    _Order_QueryPayment_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _Order_Refund_Handler,
		},
		{
			MethodName: "CloseOrder",
			Handler:    _Order_CloseOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
