// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- 秒杀下单 ----
type SeckillOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillOrderRequest) Reset() {
	*x = SeckillOrderRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillOrderRequest) ProtoMessage() {}

func (x *SeckillOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillOrderRequest.ProtoReflect.Descriptor instead.
func (*SeckillOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SeckillOrderRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *SeckillOrderRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type SeckillOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillOrderResponse) Reset() {
	*x = SeckillOrderResponse{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillOrderResponse) ProtoMessage() {}

func (x *SeckillOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillOrderResponse.ProtoReflect.Descriptor instead.
func (*SeckillOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillOrderResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *SeckillOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SeckillOrderResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ---- 创建秒杀活动 ----
type CreateSeckillActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SeckillPrice  float64                `protobuf:"fixed64,2,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`
	StockNum      int32                  `protobuf:"varint,3,opt,name=stock_num,json=stockNum,proto3" json:"stock_num,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // unix timestamp
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeckillActivityRequest) Reset() {
	*x = CreateSeckillActivityRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeckillActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeckillActivityRequest) ProtoMessage() {}

func (x *CreateSeckillActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeckillActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateSeckillActivityRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSeckillActivityRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateSeckillActivityRequest) GetSeckillPrice() float64 {
	if x != nil {
		return x.SeckillPrice
	}
	return 0
}

func (x *CreateSeckillActivityRequest) GetStockNum() int32 {
	if x != nil {
		return x.StockNum
	}
	return 0
}

func (x *CreateSeckillActivityRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateSeckillActivityRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type CreateSeckillActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint32                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeckillActivityResponse) Reset() {
	*x = CreateSeckillActivityResponse{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeckillActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeckillActivityResponse) ProtoMessage() {}

func (x *CreateSeckillActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeckillActivityResponse.ProtoReflect.Descriptor instead.
func (*CreateSeckillActivityResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSeckillActivityResponse) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *CreateSeckillActivityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSeckillActivityResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ---- 查询秒杀活动 ----
type GetSeckillActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint32                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillActivityRequest) Reset() {
	*x = GetSeckillActivityRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillActivityRequest) ProtoMessage() {}

func (x *GetSeckillActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillActivityRequest.ProtoReflect.Descriptor instead.
func (*GetSeckillActivityRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetSeckillActivityRequest) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type GetSeckillActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint32                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SeckillPrice  float64                `protobuf:"fixed64,3,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`
	StockNum      int32                  `protobuf:"varint,4,opt,name=stock_num,json=stockNum,proto3" json:"stock_num,omitempty"`
	SurplusStock  int32                  `protobuf:"varint,5,opt,name=surplus_stock,json=surplusStock,proto3" json:"surplus_stock,omitempty"`
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Success       bool                   `protobuf:"varint,9,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,10,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillActivityResponse) Reset() {
	*x = GetSeckillActivityResponse{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillActivityResponse) ProtoMessage() {}

func (x *GetSeckillActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillActivityResponse.ProtoReflect.Descriptor instead.
func (*GetSeckillActivityResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetSeckillActivityResponse) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GetSeckillActivityResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetSeckillActivityResponse) GetSeckillPrice() float64 {
	if x != nil {
		return x.SeckillPrice
	}
	return 0
}

func (x *GetSeckillActivityResponse) GetStockNum() int32 {
	if x != nil {
		return x.StockNum
	}
	return 0
}

func (x *GetSeckillActivityResponse) GetSurplusStock() int32 {
	if x != nil {
		return x.SurplusStock
	}
	return 0
}

func (x *GetSeckillActivityResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetSeckillActivityResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetSeckillActivityResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetSeckillActivityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSeckillActivityResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ---- 预热库存到Redis ----
type LoadSeckillStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint32                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSeckillStockRequest) Reset() {
	*x = LoadSeckillStockRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSeckillStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSeckillStockRequest) ProtoMessage() {}

func (x *LoadSeckillStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSeckillStockRequest.ProtoReflect.Descriptor instead.
func (*LoadSeckillStockRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *LoadSeckillStockRequest) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type LoadSeckillStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSeckillStockResponse) Reset() {
	*x = LoadSeckillStockResponse{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSeckillStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSeckillStockResponse) ProtoMessage() {}

func (x *LoadSeckillStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSeckillStockResponse.ProtoReflect.Descriptor instead.
func (*LoadSeckillStockResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *LoadSeckillStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadSeckillStockResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ---- 查询秒杀订单 ----
type GetSeckillOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillOrderRequest) Reset() {
	*x = GetSeckillOrderRequest{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillOrderRequest) ProtoMessage() {}

func (x *GetSeckillOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillOrderRequest.ProtoReflect.Descriptor instead.
func (*GetSeckillOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetSeckillOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetSeckillOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderNo           string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId            int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount       float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PayAmount         float64                `protobuf:"fixed64,4,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	OrderStatus       int32                  `protobuf:"varint,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	OrderType         int32                  `protobuf:"varint,6,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	SeckillActivityId int64                  `protobuf:"varint,7,opt,name=seckill_activity_id,json=seckillActivityId,proto3" json:"seckill_activity_id,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Success           bool                   `protobuf:"varint,9,opt,name=success,proto3" json:"success,omitempty"`
	Msg               string                 `protobuf:"bytes,10,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSeckillOrderResponse) Reset() {
	*x = GetSeckillOrderResponse{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillOrderResponse) ProtoMessage() {}

func (x *GetSeckillOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillOrderResponse.ProtoReflect.Descriptor instead.
func (*GetSeckillOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetSeckillOrderResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetSeckillOrderResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSeckillOrderResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetSeckillOrderResponse) GetPayAmount() float64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *GetSeckillOrderResponse) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *GetSeckillOrderResponse) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *GetSeckillOrderResponse) GetSeckillActivityId() int64 {
	if x != nil {
		return x.SeckillActivityId
	}
	return 0
}

func (x *GetSeckillOrderResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetSeckillOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSeckillOrderResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ---- 用户秒杀订单列表 ----
type GetUserSeckillOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSeckillOrdersRequest) Reset() {
	*x = GetUserSeckillOrdersRequest{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSeckillOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSeckillOrdersRequest) ProtoMessage() {}

func (x *GetUserSeckillOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSeckillOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetUserSeckillOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserSeckillOrdersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserSeckillOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserSeckillOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SeckillOrderInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderNo           string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId            int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount       float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PayAmount         float64                `protobuf:"fixed64,4,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	OrderStatus       int32                  `protobuf:"varint,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	SeckillActivityId int64                  `protobuf:"varint,6,opt,name=seckill_activity_id,json=seckillActivityId,proto3" json:"seckill_activity_id,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SeckillOrderInfo) Reset() {
	*x = SeckillOrderInfo{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillOrderInfo) ProtoMessage() {}

func (x *SeckillOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillOrderInfo.ProtoReflect.Descriptor instead.
func (*SeckillOrderInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *SeckillOrderInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *SeckillOrderInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SeckillOrderInfo) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *SeckillOrderInfo) GetPayAmount() float64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *SeckillOrderInfo) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *SeckillOrderInfo) GetSeckillActivityId() int64 {
	if x != nil {
		return x.SeckillActivityId
	}
	return 0
}

func (x *SeckillOrderInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetUserSeckillOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*SeckillOrderInfo    `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSeckillOrdersResponse) Reset() {
	*x = GetUserSeckillOrdersResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSeckillOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSeckillOrdersResponse) ProtoMessage() {}

func (x *GetUserSeckillOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSeckillOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetUserSeckillOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserSeckillOrdersResponse) GetOrders() []*SeckillOrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GetUserSeckillOrdersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUserSeckillOrdersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserSeckillOrdersResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ---- 取消超时订单 ----
type CancelTimeoutOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTimeoutOrderRequest) Reset() {
	*x = CancelTimeoutOrderRequest{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTimeoutOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTimeoutOrderRequest) ProtoMessage() {}

func (x *CancelTimeoutOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTimeoutOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelTimeoutOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *CancelTimeoutOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type CancelTimeoutOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTimeoutOrderResponse) Reset() {
	*x = CancelTimeoutOrderResponse{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTimeoutOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTimeoutOrderResponse) ProtoMessage() {}

func (x *CancelTimeoutOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTimeoutOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelTimeoutOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *CancelTimeoutOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTimeoutOrderResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"n\n" +
	"\x13SeckillOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\"]\n" +
	"\x14SeckillOrderResponse\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\xb9\x01\n" +
	"\x1cCreateSeckillActivityRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12#\n" +
	"\rseckill_price\x18\x02 \x01(\x01R\fseckillPrice\x12\x1b\n" +
	"\tstock_num\x18\x03 \x01(\x05R\bstockNum\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\"l\n" +
	"\x1dCreateSeckillActivityResponse\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\rR\n" +
	"activityId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"<\n" +
	"\x19GetSeckillActivityRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\rR\n" +
	"activityId\"\xc1\x02\n" +
	"\x1aGetSeckillActivityResponse\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\rR\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12#\n" +
	"\rseckill_price\x18\x03 \x01(\x01R\fseckillPrice\x12\x1b\n" +
	"\tstock_num\x18\x04 \x01(\x05R\bstockNum\x12#\n" +
	"\rsurplus_stock\x18\x05 \x01(\x05R\fsurplusStock\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x18\n" +
	"\asuccess\x18\t \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\n" +
	" \x01(\tR\x03msg\":\n" +
	"\x17LoadSeckillStockRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\rR\n" +
	"activityId\"F\n" +
	"\x18LoadSeckillStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"3\n" +
	"\x16GetSeckillOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"\xcc\x02\n" +
	"\x17GetSeckillOrderResponse\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x04 \x01(\x01R\tpayAmount\x12!\n" +
	"\forder_status\x18\x05 \x01(\x05R\vorderStatus\x12\x1d\n" +
	"\n" +
	"order_type\x18\x06 \x01(\x05R\torderType\x12.\n" +
	"\x13seckill_activity_id\x18\a \x01(\x03R\x11seckillActivityId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x18\n" +
	"\asuccess\x18\t \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\n" +
	" \x01(\tR\x03msg\"g\n" +
	"\x1bGetUserSeckillOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xfa\x01\n" +
	"\x10SeckillOrderInfo\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x04 \x01(\x01R\tpayAmount\x12!\n" +
	"\forder_status\x18\x05 \x01(\x05R\vorderStatus\x12.\n" +
	"\x13seckill_activity_id\x18\x06 \x01(\x03R\x11seckillActivityId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\x91\x01\n" +
	"\x1cGetUserSeckillOrdersResponse\x12/\n" +
	"\x06orders\x18\x01 \x03(\v2\x17.order.SeckillOrderInfoR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\"6\n" +
	"\x19CancelTimeoutOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"H\n" +
	"\x1aCancelTimeoutOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xf2\x04\n" +
	"\x05Order\x12G\n" +
	"\fSeckillOrder\x12\x1a.order.SeckillOrderRequest\x1a\x1b.order.SeckillOrderResponse\x12b\n" +
	"\x15CreateSeckillActivity\x12#.order.CreateSeckillActivityRequest\x1a$.order.CreateSeckillActivityResponse\x12Y\n" +
	"\x12GetSeckillActivity\x12 .order.GetSeckillActivityRequest\x1a!.order.GetSeckillActivityResponse\x12S\n" +
	"\x10LoadSeckillStock\x12\x1e.order.LoadSeckillStockRequest\x1a\x1f.order.LoadSeckillStockResponse\x12P\n" +
	"\x0fGetSeckillOrder\x12\x1d.order.GetSeckillOrderRequest\x1a\x1e.order.GetSeckillOrderResponse\x12_\n" +
	"\x14GetUserSeckillOrders\x12\".order.GetUserSeckillOrdersRequest\x1a#.order.GetUserSeckillOrdersResponse\x12Y\n" +
	"\x12CancelTimeoutOrder\x12 .order.CancelTimeoutOrderRequest\x1a!.order.CancelTimeoutOrderResponseB\tZ\a./orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_order_proto_goTypes = []any{
	(*SeckillOrderRequest)(nil),           // 0: order.SeckillOrderRequest
	(*SeckillOrderResponse)(nil),          // 1: order.SeckillOrderResponse
	(*CreateSeckillActivityRequest)(nil),  // 2: order.CreateSeckillActivityRequest
	(*CreateSeckillActivityResponse)(nil), // 3: order.CreateSeckillActivityResponse
	(*GetSeckillActivityRequest)(nil),     // 4: order.GetSeckillActivityRequest
	(*GetSeckillActivityResponse)(nil),    // 5: order.GetSeckillActivityResponse
	(*LoadSeckillStockRequest)(nil),       // 6: order.LoadSeckillStockRequest
	(*LoadSeckillStockResponse)(nil),      // 7: order.LoadSeckillStockResponse
	(*GetSeckillOrderRequest)(nil),        // 8: order.GetSeckillOrderRequest
	(*GetSeckillOrderResponse)(nil),       // 9: order.GetSeckillOrderResponse
	(*GetUserSeckillOrdersRequest)(nil),   // 10: order.GetUserSeckillOrdersRequest
	(*SeckillOrderInfo)(nil),              // 11: order.SeckillOrderInfo
	(*GetUserSeckillOrdersResponse)(nil),  // 12: order.GetUserSeckillOrdersResponse
	(*CancelTimeoutOrderRequest)(nil),     // 13: order.CancelTimeoutOrderRequest
	(*CancelTimeoutOrderResponse)(nil),    // 14: order.CancelTimeoutOrderResponse
}
var file_order_proto_depIdxs = []int32{
	11, // 0: order.GetUserSeckillOrdersResponse.orders:type_name -> order.SeckillOrderInfo
	0,  // 1: order.Order.SeckillOrder:input_type -> order.SeckillOrderRequest
	2,  // 2: order.Order.CreateSeckillActivity:input_type -> order.CreateSeckillActivityRequest
	4,  // 3: order.Order.GetSeckillActivity:input_type -> order.GetSeckillActivityRequest
	6,  // 4: order.Order.LoadSeckillStock:input_type -> order.LoadSeckillStockRequest
	8,  // 5: order.Order.GetSeckillOrder:input_type -> order.GetSeckillOrderRequest
	10, // 6: order.Order.GetUserSeckillOrders:input_type -> order.GetUserSeckillOrdersRequest
	13, // 7: order.Order.CancelTimeoutOrder:input_type -> order.CancelTimeoutOrderRequest
	1,  // 8: order.Order.SeckillOrder:output_type -> order.SeckillOrderResponse
	3,  // 9: order.Order.CreateSeckillActivity:output_type -> order.CreateSeckillActivityResponse
	5,  // 10: order.Order.GetSeckillActivity:output_type -> order.GetSeckillActivityResponse
	7,  // 11: order.Order.LoadSeckillStock:output_type -> order.LoadSeckillStockResponse
	9,  // 12: order.Order.GetSeckillOrder:output_type -> order.GetSeckillOrderResponse
	12, // 13: order.Order.GetUserSeckillOrders:output_type -> order.GetUserSeckillOrdersResponse
	14, // 14: order.Order.CancelTimeoutOrder:output_type -> order.CancelTimeoutOrderResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
