// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"

	"order/internal/logic"
	"order/internal/svc"
	"order/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) SeckillOrder(ctx context.Context, in *order.SeckillOrderRequest) (*order.SeckillOrderResponse, error) {
	l := logic.NewSeckillOrderLogic(ctx, s.svcCtx)
	return l.SeckillOrder(in)
}
