// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package order_client

import (
	"context"

	"order/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SeckillOrderRequest  = order.SeckillOrderRequest
	SeckillOrderResponse = order.SeckillOrderResponse

	Order interface {
		SeckillOrder(ctx context.Context, in *SeckillOrderRequest, opts ...grpc.CallOption) (*SeckillOrderResponse, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) SeckillOrder(ctx context.Context, in *SeckillOrderRequest, opts ...grpc.CallOption) (*SeckillOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.SeckillOrder(ctx, in, opts...)
}
